# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "docker-host-websocket"
  config.vm.box_check_update = false
  config.ssh.insert_key = false
  config.vm.box = "phusion/ubuntu-14.04-amd64"
  config.vm.provision "docker"
  config.vm.network :forwarded_port, host: 8080, guest: 8080
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
